apiVersion: v1
kind: Secret
metadata:
  name: storehub-credentials
  annotations:
    application-name: "StoreHub"
    component: "Secrets for environment variables"
type: Opaque
stringData:
  connectionString: "blah"
  sumologicUrl: "blah"
  instanceUrl: "blah"
  instanceApiKey: "blah"
  environment: "Development"
  openFeatureClientId: "blah"
